# argocd yaml 배포 파일  
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service3
spec:
  selector:
    app: my-nginx-app3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx-app3
  template:
    metadata:
      labels:
        app: my-nginx-app3
    spec:
      containers:
        - name: my-nginx-container
          image: rlaaudgus/my-test3:latest  # 위에서 빌드한 이미지 이름
          ports:
            - containerPort: 80
